<?php

/**
 * @file
 * The main Islandora CONTENTdm API module file.
 */

/**
 * Implements hook_menu().
 */
function islandora_cdm_api_menu() {
  $items = array();
  $items['admin/islandora/tools/cdm_api'] = array(
    'title' => 'CONTENTdm API',
    'description' => 'Configure the Islandora CONTENTdm API module.',
    'page callback' => 'drupal_get_form',
    'access arguments' => array('administer site configuration'),
    'page arguments' => array('islandora_cdm_api_admin_settings'),
    'type' => MENU_NORMAL_ITEM,
  );
  $items['islandora_cdm_api/dmGetCollectionsList/%'] = array(
    'title' => 'dmGetCollectionsList',
    'description' => '',
    'page callback' => 'islandora_cdm_api_dmgetcollectionslist',
    'page arguments' => array(2),
    'access arguments' => array('access contentdm api'),
    'type' => MENU_LOCAL_TASK,
  );
  $items['islandora_cdm_api/dmGetDublinCoreFieldInfo/%'] = array(
    'title' => 'dmGetDublinCoreFieldInfo',
    'description' => '',
    'page callback' => 'islandora_cdm_api_dmgetdublincorefieldinfo',
    'page arguments' => array(2),
    'access arguments' => array('access contentdm api'),
    'type' => MENU_LOCAL_TASK,
  );
  $items['islandora_cdm_api/dmGetCollectionFieldInfo/%/%'] = array(
    'title' => 'dmGetCollectionFieldInfo',
    'description' => '',
    'page callback' => 'islandora_cdm_api_dmgetcollectionfieldinfo',
    'page arguments' => array(2, 3),
    'access arguments' => array('access contentdm api'),
    'type' => MENU_LOCAL_TASK,
  );
  $items['islandora_cdm_api/dmGetCollectionParameters/%/%'] = array(
    'title' => 'dmGetCollectionParameters',
    'description' => '',
    'page callback' => 'islandora_cdm_api_dmgetcollectionparameters',
    'page arguments' => array(2, 3),
    'access arguments' => array('access contentdm api'),
    'type' => MENU_LOCAL_TASK,
  );
  $items['islandora_cdm_api/dmGetCompoundObjectInfo/%/%/%'] = array(
    'title' => 'dmGetCompoundObjectInfo',
    'description' => '',
    'page callback' => 'islandora_cdm_api_dmgetcompoundobjectinfo',
    'page arguments' => array(2, 3, 4),
    'access arguments' => array('access contentdm api'),
    'type' => MENU_LOCAL_TASK,
  );
  $items['islandora_cdm_api/dmGetImageInfo/%/%/%'] = array(
    'title' => 'dmGetImageInfo',
    'description' => '',
    'page callback' => 'islandora_cdm_api_dmgetimageinfo',
    'page arguments' => array(2, 3, 4),
    'access arguments' => array('access contentdm api'),
    'type' => MENU_LOCAL_TASK,
  );
  $items['islandora_cdm_api/dmGetItemInfo/%/%/%'] = array(
    'title' => 'dmGetItemInfo',
    'description' => '',
    'page callback' => 'islandora_cdm_api_dmgetiteminfo',
    'page arguments' => array(2, 3, 4),
    'access arguments' => array('access contentdm api'),
    'type' => MENU_LOCAL_TASK,
  );
  // Problem: dmQuery requires 15 path segments, but Drupal can only handle 9:
  // https://api.drupal.org/api/drupal/includes!menu.inc/constant/MENU_MAX_PARTS/7
  // $items['islandora_cdm_api/dmQuery/%/%/%/%/%/%/%/%/%/%/%/%/%'] = array(
  $items['islandora_cdm_api/dmQuery/%'] = array(
    'title' => 'dmQuery',
    'description' => '',
    'page callback' => 'islandora_cdm_api_dmquery',
    // 'page arguments' => array(2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14),
    'page arguments' => array(2),
    'access arguments' => array('access contentdm api'),
    'type' => MENU_LOCAL_TASK,
  );
  $items['islandora_cdm_api/GetItemDmmodified/%/%/%'] = array(
    'title' => 'GetItemDmmodified',
    'description' => '',
    'page callback' => 'islandora_cdm_api_getitemdmmodified',
    'page arguments' => array(2, 3, 4),
    'access arguments' => array('access contentdm api'),
    'type' => MENU_LOCAL_TASK,
  );
  $items['islandora_cdm_api/GetParent/%/%/%'] = array(
    'title' => 'GetParent',
    'description' => '',
    'page callback' => 'islandora_cdm_api_getparent',
    'page arguments' => array(2, 3, 4),
    'access arguments' => array('access contentdm api'),
    'type' => MENU_LOCAL_TASK,
  );
  $items['islandora_cdm_api/utils/getfile/collection/%/id/%/filename/%'] = array(
    'title' => 'GetFile',
    'description' => '',
    'page callback' => 'islandora_cdm_api_getfile',
    'page arguments' => array(4, 6, 8),
    'access arguments' => array('access contentdm api'),
    'type' => MENU_LOCAL_TASK,
  );
  $items['islandora_cdm_api/utils/ajaxhelper'] = array(
    'title' => 'GetImage',
    'description' => '',
    'page callback' => 'islandora_cdm_api_getimage',
    // 'page arguments' => array(4, 6, 8),
    'access arguments' => array('access contentdm api'),
    'type' => MENU_LOCAL_TASK,
  );
  $items['islandora_cdm_api/utils/getstream/collection/%/id/%'] = array(
    'title' => 'GetStream',
    'description' => '',
    'page callback' => 'islandora_cdm_api_getstream',
    'page arguments' => array(4, 6),
    'access arguments' => array('access contentdm api'),
    'type' => MENU_LOCAL_TASK,
  );
  $items['islandora_cdm_api/utils/getthumbnail/collection/%/id/%'] = array(
    'title' => 'GetThumbnail',
    'description' => '',
    'page callback' => 'islandora_cdm_api_getthumbnail',
    'page arguments' => array(4, 6),
    'access arguments' => array('access contentdm api'),
    'type' => MENU_LOCAL_TASK,
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function islandora_cdm_api_permission() {
  return array(
    'access contentdm api' => array(
      'title' => t('Access CONTENTdm API'),
      'description' => t('Access the CONTENTdm API'),
    ),
  );
}

/**
 * Admin settings form builder.
 */
function islandora_cdm_api_admin_settings() {
  $form = array();
  $form['islandora_cdm_api_test'] = array(
    '#title' => t('Your name please'),
    '#type' => 'textfield',
    '#size' => 60,
    // '#default_value' => variable_get('islandora_bagit_library_dir', 'BagItPHP'),
    '#description' => t("What's your name."),
    '#maxlength' => 255,
  );

  return system_settings_form($form);
}

function islandora_cdm_api_dmgetcollectionslist($format = 'json') {
  $data = array('dmGetCollectionsList', $format);
  drupal_json_output($data);
}

function islandora_cdm_api_dmgetdublincorefieldinfo($format = 'json') {
  $data = array('dmGetDublinCoreFieldInfo', $format);
  drupal_json_output($data);
}

function islandora_cdm_api_dmgetcollectionfieldinfo($alias = '', $format = 'json') {
  $data = array('dmGetCollectionFieldInfo', $alias, $format);
  drupal_json_output($data);
}

function islandora_cdm_api_dmgetcollectionparameters($alias = '', $format = 'json') {
  $data = array('dmGetCollectionParameters', $alias, $format);
  drupal_json_output($data);
}

function islandora_cdm_api_dmgetcompoundobjectinfo($alias = '', $pointer = '', $format = 'json') {
  $data = array('dmGetCompoundObjectInfo', $alias, $pointer, $format);
  drupal_json_output($data);
}

function islandora_cdm_api_dmgetimageinfo($alias = '', $pointer = '', $format = 'json') {
  $data = array('dmGetImageInfo', $alias, $pointer, $format);
  drupal_json_output($data);
}

function islandora_cdm_api_dmgetiteminfo($alias = '', $pointer = '', $format = 'json') {
  $data = array('dmGetItemInfo', $alias, $pointer, $format);
  drupal_json_output($data);
}

// function islandora_cdm_api_dmquery($alias = '', $searchstrings = '', $fields = '', $sortby = '', $maxrecs = '1024', $start = '0', $supress = '0', $docptr = '0', $suggest = '0', $facets = '0', $showunpub = '0', $denormalizedFacets = '0', $format = 'json') {
function islandora_cdm_api_dmquery($paramstring) {
  // $data = array('dmQuery', $alias, $searchstrings, $fields, $sortby, $maxrecs, $start, $supress, $docptr, $suggest, $facets, $showunpub, $denormalizedFacets, $format);
  $data = array('dmQuery', $paramstring);
  // drupal_json_output($data);
  drupal_json_output($data);
}

function islandora_cdm_api_getitemdmmodified($alias = '', $pointer = '', $format = 'json') {
  $data = array('GetItemDmmodified', $alias, $pointer, $format);
  drupal_json_output($data);
}

function islandora_cdm_api_getparent($alias = '', $pointer = '', $format = 'json') {
  $data = array('GetParent', $alias, $pointer, $format);
  drupal_json_output($data);
}

/*
 The file functions should use the following:

 module_load_include('inc', 'islandora', 'includes/datastream');
 islandora_download_datastream($datastream);
*/

function islandora_cdm_api_getfile($alias = 'foo', $pointer = 'bar', $filename = 'baz') {
  $data = array('GetFile', $alias, $pointer, $filename);
  drupal_json_output($data);
}

/**
 * GetImage uses $_GET, not menu arguments.
 */
function islandora_cdm_api_getimage() {
  $data = drupal_get_query_parameters();
  drupal_json_output(array('Request' => 'GetImage') + $data);
}

function islandora_cdm_api_getstream($alias = 'foo', $pointer = 'bar') {
  $data = array('GetStream', $alias, $pointer);
  drupal_json_output($data);
}

function islandora_cdm_api_getthumbnail($alias = 'foo', $pointer = 'bar') {
  $data = array('GetThumbnail', $alias, $pointer);
  drupal_json_output(array('Request' => 'getthumbnail') + $data);
}

