<?php

/**
 * @file
 * The main Islandora CONTENTdm API module file.
 */

/**
 * Implements hook_menu().
 */
function islandora_cdm_api_menu() {
  $items = array();
  $items['admin/islandora/tools/cdm_api'] = array(
    'title' => 'CONTENTdm API Provider',
    'description' => 'Configure the Islandora CONTENTdm API Provider module.',
    'page callback' => 'drupal_get_form',
    'access arguments' => array('administer site configuration'),
    'page arguments' => array('islandora_cdm_api_admin_settings'),
    'type' => MENU_CALLBACK,
  );
  // We can't use ordinary menu paths for most of the CONTENTdm API URLs
  // because Drupal menu paths have a maximum of 9 path segments. See
  // https://api.drupal.org/api/drupal/includes!menu.inc/constant/
  // MENU_MAX_PARTS/7. To get around this, we consider everything in
  // the incoming request's query (?c=) to be a single string that we
  // parse to get the "parameters". We can't use ?q= because Drupal uses
  // it already for its parameters.
  $items['cdm_api'] = array(
    'title' => 'CONTENTdm API',
    'page callback' => 'islandora_cdm_api_router',
    'access arguments' => array('access contentdm api'),
    'type' => MENU_CALLBACK,
  );
  $items['cdm_api/utils/getfile/collection/%/id/%/filename/%'] = array(
    'title' => 'GetFile',
    'page callback' => 'islandora_cdm_api_getfile',
    'page arguments' => array(4, 6, 8),
    'access arguments' => array('access contentdm api'),
    'type' => MENU_CALLBACK,
  );
  $items['cdm_api/utils/ajaxhelper'] = array(
    'title' => 'GetImage',
    'page callback' => 'islandora_cdm_api_getimage',
    'access arguments' => array('access contentdm api'),
    'type' => MENU_CALLBACK,
  );
  $items['cdm_api/utils/getstream/collection/%/id/%'] = array(
    'title' => 'GetStream',
    'page callback' => 'islandora_cdm_api_getstream',
    'page arguments' => array(4, 6),
    'access arguments' => array('access contentdm api'),
    'type' => MENU_CALLBACK,
  );
  $items['cdm_api/utils/getthumbnail/collection/%/id/%'] = array(
    'title' => 'GetThumbnail',
    'page callback' => 'islandora_cdm_api_getthumbnail',
    'page arguments' => array(4, 6),
    'access arguments' => array('access contentdm api'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * Implements hook_permission().
 */
function islandora_cdm_api_permission() {
  return array(
    'access contentdm api' => array(
      'title' => t('Access CONTENTdm API'),
      'description' => t('Access the CONTENTdm API'),
    ),
  );
}

/**
 * Admin settings form builder.
 */
function islandora_cdm_api_admin_settings() {
  $form = array();
  $form['islandora_cdm_api_source_cdm_url'] = array(
    '#title' => t('Source CONTENTdm server hostname'),
    '#type' => 'textfield',
    '#size' => 60,
    '#default_value' => variable_get('islandora_cdm_api_source_cdm_url', 'http://contentdm.example.com'),
    '#description' => t('The hostname of the CONTENTdm server that the Islandora objects were migrated from. Include the "http://" or "https://" but not the trailing slash.'),
    '#maxlength' => 60,
  );
  $form['islandora_cdm_api_identifier_element'] = array(
    '#title' => t('Identifier element'),
    '#type' => 'textfield',
    '#size' => 60,
    '#default_value' => variable_get('islandora_cdm_api_identifier_element', 'dc.identifier'),
    '#description' => t('The element to specify in the Solr query to find CONTENTdm reference URLs. MODS <identifier> elements get mapped to dc.identifer automatically, so if your MODS stores the CONTENTdm reference URLs there, use dc.identifier.'),
    '#maxlength' => 60,
  );
  return system_settings_form($form);
}

/**
 * Routes from query string values to functions.
 *
 * Grabs the query string from the request and passes it off to the appropriate
 * function. We need to use a query string instead of menu path elements since
 * Drupal 7 only allows 9 of these, and dmQuery requires more than that. See
 * https://api.drupal.org/api/drupal/includes!menu.inc/constant/MENU_MAX_PARTS/7
 * for the Drupal menu limitation. So we handle all of the API requests the same
 * way, we route them through a single menu callback.
 */
function islandora_cdm_api_router() {
  $not_recognized_message = t('Your request to the CONTENTdm API was not recognized.');
  $query = drupal_get_query_parameters();
  if (!count($query)) {
    return $not_recognized_message;
  }

  // The string we want is the only key ('c') in the query.
  $query_string = $query['c'];
  $params = explode('/', $query_string);
  // Get the first item after the question mark and pass the remainder
  // of the exploded string to the switch.
  $verb = array_shift($params);

  switch ($verb) {
    case 'dmGetCollectionsList':
      islandora_cdm_api_dmgetcollectionslist($params);
      break;

    case 'dmGetDublinCoreFieldInfo':
      islandora_cdm_api_dmgetdublincorefieldinfo($params);
      break;

    case 'dmGetCollectionFieldInfo':
      islandora_cdm_api_dmgetcollectionfieldinfo($params);
      break;

    case 'dmGetCollectionParameters':
      islandora_cdm_api_dmgetcollectionparameters($params);
      break;

    case 'dmGetCompoundObjectInfo':
      islandora_cdm_api_dmgetcompoundobjectinfo($params);
      break;

    case 'dmGetImageInfo':
      islandora_cdm_api_dmgetimageinfo($params);
      break;

    case 'dmGetItemInfo':
      islandora_cdm_api_dmgetiteminfo($params);
      break;

    case 'dmQuery':
      islandora_cdm_api_dmquery($params);
      break;

    case 'GetItemDmmodified':
      islandora_cdm_api_getitemdmmodified($params);
      break;

    case 'GetParent':
      islandora_cdm_api_getparent($params);
      break;

    default:
      return $not_recognized_message;
  }
}

/**
 * CONTENTdm API callback.
 *
 * @param array $params
 *   An array containing the format.
 */
function islandora_cdm_api_dmgetcollectionslist($params) {
}

/**
 * CONTENTdm API callback.
 *
 * @param array $params
 *   An array containing the format.
 */
function islandora_cdm_api_dmgetdublincorefieldinfo($params) {
  $path = drupal_get_path('module', 'islandora_cdm_api');
  if ($params[0] == 'xml') {
    $path_to_file = $path . '/includes/dmGetDublinCoreFieldInfo.xml';
    $xml = file_get_contents($path_to_file);
    drupal_add_http_header('Content-Type', 'text/xml; utf-8');
    print $xml;
  }
  if ($params[0] == 'json') {
    $path_to_file = $path . '/includes/dmGetDublinCoreFieldInfo.json';
    $json = file_get_contents($path_to_file);
    drupal_add_http_header('Content-Type', 'application/json; utf-8');
    print $json;
  }
}

/**
 * CONTENTdm API callback.
 *
 * @param array $params
 *   An array containing the alias and format.
 */
function islandora_cdm_api_dmgetcollectionfieldinfo($params) {
}

/**
 * CONTENTdm API callback.
 *
 * @param array $params
 *   An array containing the alias and format.
 */
function islandora_cdm_api_dmgetcollectionparameters($params) {
}

/**
 * CONTENTdm API callback.
 *
 * @param array $params
 *   An array containing the alias, pointer and format from the URL.
 */
function islandora_cdm_api_dmgetcompoundobjectinfo($params) {
  $islandora_object_pid = islandora_cdm_api_map_request_to_pid($params[0], $params[1]);
}

/**
 * CONTENTdm API callback.
 *
 * @param array $params
 *   An array containing the alias, pointer and format.
 */
function islandora_cdm_api_dmgetimageinfo($params) {
  module_load_include('inc', 'islandora_cdm_api', 'includes/utilities');
  if (!$islandora_object_pid = islandora_cdm_api_map_request_to_pid($params[0], $params[1])) {
    print '<?xml version="1.0" encoding="UTF-8"?><error>Record does not exist</error>';
  }
  // Contrary to the API documentation, CONTENTdm returns this error XML
  // if you ask for 'json'.
  if ($params[2] == 'json') {
    print '<?xml version="1.0" encoding="UTF-8"?><error>Record does not exist</error>';
  }
  $object = islandora_object_load($islandora_object_pid);
  $object_cmodels = $object->relationships->get('info:fedora/fedora-system:def/model#', 'hasModel');
  // The object must have one of these content models.
  if ($object_cmodels[0]['object']['value'] == 'islandora:sp_basic_image') {
    $dsid = 'OBJ';
  }
  // This approach prefers JPG, then JP2, then OBJ.
  if ($object_cmodels[0]['object']['value'] == 'islandora:sp_large_image_cmodel') {
    if (isset($object['JPG'])) {
      $dsid = 'JPG';
    }
    elseif (isset($object['JP2'])) {
      $dsid = 'JP2';
    }
    elseif (isset($object['OBJ'])) {
      $dsid = 'OBJ';
    }
    else {
      // drupal_not_found ?
    }
  }
  $image_file = file_save_data($object[$dsid]->content, 'temporary://');
  $real_path = drupal_realpath($image_file->uri);
  $info = image_get_info($real_path);
  if (empty($info)) {
    // @todo: Figure out what to return if the info is not availble.
  }
  file_delete($image_file);
  $xml = new XMLWriter();
  $xml->openMemory();
  $xml->startDocument('1.0', 'UTF-8');
  $xml->startElement('imageinfo');
  $xml->writeElement('filename', '');
  $xml->writeElement('type', $info['extension']);
  $xml->writeElement('width', $info['width']);
  $xml->writeElement('height', $info['height']);
  $xml->writeElement('title', $object->label);
  $xml->endElement();
  drupal_add_http_header('Content-Type: text/xml; utf-8');
  print $xml->outputMemory();
}

/**
 * CONTENTdm API callback.
 *
 * @param array $params
 *   An array containing the alias, pointer and format.
 */
function islandora_cdm_api_dmgetiteminfo($params) {
  $islandora_object_pid = islandora_cdm_api_map_request_to_pid($params[0], $params[1]);
}

/**
 * CONTENTdm API callback.
 *
 * @param array $params
 *   An array containing the alias, searchstrings, fields,
 *   sortby, maxrecs, start, suppress, docptr, suggest,
 *   facets, showunpub, denormalizedFacets, and format.
 */
function islandora_cdm_api_dmquery($params) {
  // $alias = '', $searchstrings = '', $fields = '', $sortby = '',
  // $maxrecs = '1024', $start = '0', $supress = '0', $docptr = '0',
  // $suggest = '0', $facets = '0', $showunpub = '0', $denormalizedFacets = '0',
  // $format = 'json'.
}

/**
 * CONTENTdm API callback.
 *
 * @param array $params
 *   An array containing the alias, pointer and format.
 */
function islandora_cdm_api_getitemdmmodified($params) {
  module_load_include('inc', 'islandora_cdm_api', 'includes/utilities');
  if (!$islandora_object_pid = islandora_cdm_api_map_request_to_pid($params[0], $params[1])) {
    print '<?xml version="1.0" encoding="UTF-8"?><error>Record does not exist</error>';
  }
  if ($params[2] == 'xml') {
    drupal_add_http_header('Content-Type: text/xml; utf-8');
    print '<?xml version="1.0" encoding="UTF-8"?>' .
    '<error>Sorry, output for dmGetItemDmmodified is not available in xml</error><xml>';
  }
  $object = islandora_object_load($islandora_object_pid);
  // Fedora provides 2015-01-15 03:00:06 but CONTENTdm returns 2015-01-15.
  $islandora_last_modified = $object->lastModifiedDate;
  $cdm_last_modified = preg_replace('/\s.*$/', '', $islandora_last_modified->date);
  $output = array('0', $cdm_last_modified);
  drupal_json_output($output);
}

/**
 * CONTENTdm API callback.
 *
 * @param array $params
 *   An array containing the alias, pointer and format.
 */
function islandora_cdm_api_getparent($params) {
  $islandora_object_pid = islandora_cdm_api_map_request_to_pid($params[0], $params[1]);
}

/**
 * CONTENTdm API callback.
 *
 * @param string $alias
 *   The CONTENTdm alias.
 * @param string $pointer
 *   The CONTENTdm pointer.
 * @param string $filename
 *   The filename that will be used to for the downloaded file.
 *
 * @todo: Which DSID do we choose if the object has no OBJ?
 */
function islandora_cdm_api_getfile($alias, $pointer, $filename) {
  module_load_include('inc', 'islandora_cdm_api', 'includes/utilities');
  if (!$islandora_object_pid = islandora_cdm_api_map_request_to_pid($alias, $pointer)) {
    print '<?xml version="1.0" encoding="UTF-8"?><error>Record does not exist</error>';
  }
  $object = islandora_object_load($islandora_object_pid);
  if (isset($object['OBJ'])) {
    drupal_add_http_header('Content-Type: Application/octet-stream');
    drupal_add_http_header('Content-description: ' . $filename);
    print $object['OBJ']->content;
  }
}

/**
 * CONTENTdm API callback.
 *
 * GetImage uses $_GET, not menu arguments.
 */
function islandora_cdm_api_getimage() {
  $params = drupal_get_query_parameters();
}

/**
 * CONTENTdm API callback.
 *
 * @param string $alias
 *   The CONTENTdm alias.
 * @param string $pointer
 *   The CONTENTdm pointer.
 */
function islandora_cdm_api_getstream($alias, $pointer) {
  $islandora_object_pid = islandora_cdm_api_map_request_to_pid($alias, $pointer);
}

/**
 * CONTENTdm API callback.
 *
 * @param string $alias
 *   The CONTENTdm alias.
 * @param string $pointer
 *   The CONTENTdm pointer.
 */
function islandora_cdm_api_getthumbnail($alias, $pointer) {
  if (!$islandora_object_pid = islandora_cdm_api_map_request_to_pid($alias, $pointer)) {
    print '<?xml version="1.0" encoding="UTF-8"?><error>Record does not exist</error>';
  }
  module_load_include('inc', 'islandora', 'includes/datastream');
  // Load the Islandora object.
  $object = islandora_object_load($islandora_object_pid);
  // Get its TN datastream and return its content to client.
  $tn = islandora_datastream_load('TN', $object);
  islandora_download_datastream($tn);
}
